# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/frx-challenges/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
#
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "18"
  commands:
    - mkdir $READTHEDOCS_OUTPUT
    - cd docs
    - pip install -r requirements.txt
    - myst build --html --ci --check-links
    - cp --recursive _build/* $READTHEDOCS_OUTPUT/

# Explicitly opt out of trying to build additional formats such as PDF and ePub
formats: []
