# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "frx-challenges"
  tag: "1.0.1"
  pullPolicy: IfNotPresent

web:
  resources: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  ingressClassName: nginx
  annotations: {}
  hosts: []
  path: /
  pathType: Prefix
  tls: []

pvc:
  storage: 1Gi
  storageClassName:


nodeSelector: {}

tolerations: []

affinity: {}

yamlSettings:
  enabled: false
  overrides:
    MEDIA_ROOT: /opt/state/media/
    STATIC_ROOT: /opt/staticfiles/
    DATABASES.default.NAME: /opt/state/db.sqlite3
    SUBMISSIONS_UPLOADS_DIR: /opt/state/submissions/
    SUBMISSIONS_RESULTS_DIR: /opt/state/submission-results/

adminUsers: []

nginx:
  image:
    repository: nginx
    tag: 1.27
  resources: {}

extraInitContainers: {}

evaluator:
  resources: {}

dind:
  rootless: false
  resources: {}
  image:
    repository: docker
    tag: 27.0.3-dind
