apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unnamed.fullname" . }}-nginx
data:
  default.conf: |
    server {
        listen {{ .Values.service.port }};

        # Increase the limit of
        client_max_body_size 1024m;

        location /media/ {
          alias /opt/state/media/;

          # Options for optimal local static content serving
          # From https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/
          sendfile on;
          tcp_nopush on;
        }

        location /static/ {
          alias /opt/state/static/;

          # Options for optimal local static content serving
          # From https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/
          sendfile on;
          tcp_nopush on;
        }

        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Host $http_host;
          # we don't want nginx trying to do something clever with
          # redirects, we set the Host: header above already.
          proxy_redirect off;
          proxy_pass http://127.0.0.1:8000;
        }
    }
