{{- if .Values.yamlSettings.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unnamed.fullname" . }}-django-yamlconf
data:
  comptest.yaml: |
    {{- range $key, $val := .Values.yamlSettings.overrides }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}

{{- end }}
