apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unnamed.fullname" . }}
  labels:
    {{- include "unnamed.labels" . | nindent 4 }}
spec:
  strategy:
    # We have a PVC that can be only bound to one place, so needs to Recreate
    type: Recreate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "unnamed.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "unnamed.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: db-migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /opt/unnamed-thingity-thing/comptest
          command:
            - python
            - manage.py
            - migrate
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: storage
              mountPath: /opt/state
            - name: django-yamlconf
              mountPath: /opt/unnamed-thingity-thing/comptest/comptest.yaml
              subPath: comptest.yaml
        - name: admin-add
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /opt/unnamed-thingity-thing/comptest
          command:
            - python
            - manage.py
            - promote
            - '{{ include "quoteList" .Values.adminUsers }}'
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: storage
              mountPath: /opt/state
            - name: django-yamlconf
              mountPath: /opt/unnamed-thingity-thing/comptest/comptest.yaml
              subPath: comptest.yaml
      containers:
        - name: run-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /opt/unnamed-thingity-thing/comptest
          command:
            - gunicorn
            - --bind
            - 127.0.0.1:8000
            - comptest.wsgi
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: storage
              mountPath: /opt/state
            - name: django-yamlconf
              mountPath: /opt/unnamed-thingity-thing/comptest/comptest.yaml
              subPath: comptest.yaml
        - name: nginx
          image: nginx:1.27
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: storage
              mountPath: /opt/state
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "unnamed.fullname" . }}
        - name: django-yamlconf
          configMap:
            name: {{ include "unnamed.fullname" . }}-django-yamlconf
        - name: nginx-config
          configMap:
            name: {{ include "unnamed.fullname" . }}-nginx
