apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frx-challenges.fullname" . }}
  labels:
    {{- include "frx-challenges.labels" . | nindent 4 }}
spec:
  strategy:
    # We have a PVC that can be only bound to one place, so needs to Recreate
    type: Recreate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frx-challenges.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- /* changed configmap checksums -> changed pod template -> triggers rollout */}}
        checksum/configmap-nginx: {{ include (print .Template.BasePath "/configmap-nginx.yaml") . | sha256sum }}
        checksum/configmap-yamlconf: {{ include (print .Template.BasePath "/configmap-yamlconf.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- . | nindent 8 | toYaml }}
        {{- end }}
      labels:
        {{- include "frx-challenges.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: db-migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /opt/frx-challenges/comptest
          command:
            - python
            - manage.py
            - migrate
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: storage
              mountPath: /opt/state
            - name: django-yamlconf
              mountPath: /opt/frx-challenges/comptest/comptest.yaml
              subPath: comptest.yaml
        - name: collect-static
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /opt/frx-challenges/comptest
          command:
            - python
            - manage.py
            - collectstatic
            - --noinput
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: django-yamlconf
              mountPath: /opt/frx-challenges/comptest/comptest.yaml
              subPath: comptest.yaml
            - name: staticfiles
              mountPath: /opt/staticfiles
        - name: admin-add
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /opt/frx-challenges/comptest
          command:
            - python
            - manage.py
            - promote
            - '{{ include "quoteList" .Values.adminUsers }}'
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: storage
              mountPath: /opt/state
            - name: django-yamlconf
              mountPath: /opt/frx-challenges/comptest/comptest.yaml
              subPath: comptest.yaml
        {{ with .Values.extraInitContainers }}
        {{ $extraInitContainers := . }}
        {{ $sortedKeys := keys $extraInitContainers | sortAlpha }}
        {{ range $sortedKeys }}
        - {{ get $extraInitContainers .  | toYaml | nindent 10 }}
        {{ end }}
        {{ end }}
      containers:
        - name: django
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /opt/frx-challenges/comptest
          command:
            - gunicorn
            - --bind
            - 127.0.0.1:8000
            - comptest.wsgi
          securityContext:
            runAsUser: 0
          resources: {{ toJson .Values.resources }}
          volumeMounts:
            - name: storage
              mountPath: /opt/state
            - name: django-yamlconf
              mountPath: /opt/frx-challenges/comptest/comptest.yaml
              subPath: comptest.yaml
        - name: dind
          image: {{ .Values.dind.image.repository }}:{{ .Values.dind.image.tag }}
          command:
            {{ if .Values.dind.rootless }}
            - dind
            {{- end }}
            - dockerd
            - --host=tcp://127.0.0.1:2376
          volumeMounts:
            - name: storage
              mountPath: /opt/state
          securityContext:
            privileged: true
            runAsUser: 0
          env:
            - name: DOCKER_HOST
              value: tcp://127.0.0.1:2376
        - name: evaluator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /opt/frx-challenges/comptest
          command:
            - python
            - manage.py
            - evaluator
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: storage
              mountPath: /opt/state
            - name: django-yamlconf
              mountPath: /opt/frx-challenges/comptest/comptest.yaml
              subPath: comptest.yaml
          env:
            - name: DOCKER_HOST
              value: tcp://127.0.0.1:2376
        - name: nginx
          image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
          securityContext:
            runAsUser: 0
          resources: {{ toJson .Values.nginx.resources }}
          volumeMounts:
            - name: storage
              mountPath: /opt/state
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: staticfiles
              mountPath: /opt/staticfiles
              readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "frx-challenges.fullname" . }}
        - name: staticfiles
          emptyDir: {}
        - name: django-yamlconf
          configMap:
            name: {{ include "frx-challenges.fullname" . }}-django-yamlconf
        - name: nginx-config
          configMap:
            name: {{ include "frx-challenges.fullname" . }}-nginx
