apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.pv.serverIP | quote }}
    path: "/db/{{ .Release.Name }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: {{ .Release.Name }}-db-nfs
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
