apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "unnamed.fullname" . }}
  labels:
    {{- include "unnamed.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if typeIs "string" .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
